# Generated by Django 5.1.6 on 2025-02-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1', models.CharField(default='sampleData', max_length=100)),
                ('feature2', models.CharField(default='sampleData', max_length=100)),
                ('feature3', models.CharField(default='sampleData', max_length=100)),
                ('feature4', models.CharField(default='sampleData', max_length=100)),
                ('feature5', models.CharField(default='sampleData', max_length=100)),
                ('feature6', models.CharField(default='sampleData', max_length=100)),
                ('feature7', models.CharField(default='sampleData', max_length=100)),
                ('feature8', models.CharField(default='sampleData', max_length=100)),
                ('feature9', models.CharField(default='sampleData', max_length=100)),
                ('feature10', models.CharField(default='sampleData', max_length=100)),
            ],
        ),
    ]
