# Generated by Django 5.1.6 on 2025-03-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sampletable_sampledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledata',
            old_name='feature1',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature10',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature4',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature5',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature6',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature7',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature8',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='feature9',
        ),
    ]
